apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: automated-github-branch-protection
    app.kubernetes.io/component: automated-github-branch-protection
    app.kubernetes.io/instance: automated-github-branch-protection
  name: automated-github-branch-protection
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: automated-github-branch-protection
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deploymentconfig: automated-github-branch-protection
    spec:
      containers:
      - env:
        - name: PERSONAL_TOKEN
          valueFrom:
            secretKeyRef:
              key: PERSONAL_TOKEN
              name: sec-openshift
        - name: GITHUB_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              key: GITHUB_WEBHOOK_SECRET
              name: sec-openshift
        - name: USER_AGENT
          valueFrom:
            configMapKeyRef:
              key: USER_AGENT
              name: values-git
        - name: TIME_ZONE
          valueFrom:
            configMapKeyRef:
              key: TIME_ZONE
              name: values-git
        - name: TAG_NAME
          valueFrom:
            configMapKeyRef:
              key: TAG_NAME
              name: values-git
        - name: CONTENT_FILE
          valueFrom:
            configMapKeyRef:
              key: CONTENT_FILE
              name: values-git
        - name: ORGANIZATION
          valueFrom:
            configMapKeyRef:
              key: ORGANIZATION
              name: values-git
        - name: PROTECTING_BRANCH
          valueFrom:
            configMapKeyRef:
              key: PROTECTING_BRANCH
              name: values-git
        - name: COMMITER_NAME
          valueFrom:
            configMapKeyRef:
              key: COMMITER_NAME
              name: values-git
        - name: COMMITER_EMAIL
          valueFrom:
            configMapKeyRef:
              key: COMMITER_EMAIL
              name: values-git
        - name: AUTHOR_NAME
          valueFrom:
            configMapKeyRef:
              key: AUTHOR_NAME
              name: values-git
        - name: AUTHOR_EMAIL
          valueFrom:
            configMapKeyRef:
              key: AUTHOR_EMAIL
              name: values-git
        image: image-registry.openshift-image-registry.svc:5000/protect-branch/automated-github-branch-protection@sha256:a0e73e6188e6c6f5ef28a430dde4943d9e6228e0e5bec5c62ad308533e37a95c
        imagePullPolicy: Always
        name: automated-github-branch-protection
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - automated-github-branch-protection
      from:
        kind: ImageStreamTag
        name: automated-github-branch-protection:latest
        namespace: protect-branch
    type: ImageChange
