apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: automated-github-branch-protection
    app.kubernetes.io/component: automated-github-branch-protection
    app.kubernetes.io/instance: automated-github-branch-protection
  name: automated-github-branch-protection
spec:
  clusterIP: 172.30.236.40
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    deploymentconfig: automated-github-branch-protection
  sessionAffinity: None
  type: ClusterIP